accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'), # User [C]reate
    path('', views.login, name='login'), # Session [C]reate
    path('logout/', views.logout, name='logout'), # Session [D]elete
    path('delete/', views.delete, name='delete'), # User [D]elete
    path('edit/', views.edit, name='edit'), # User [U]pdate
    path('password/', views.password, name='password'), # (Password) [U]pdate
    # path('profile/', views.profile_detail, name='profile_detail'), # Profile [R]ead
    # path('profile/edit/', views.profile_edit, name='profile_edit'), # Profile [U]pdate
    # path('<str:username>/', views.profile, name='profile'),
]

coogle/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect # new 
from django.conf import settings # new 
from django.conf.urls.static import static # new

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('documents/', include('documents.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

documents/urls.py
from django.urls import path
from . import views


app_name = 'documents'

urlpatterns = [
    path('search/', views.search, name='search'),
    path('result/', views.result, name='result'),
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    # path('result/', views.model_form_upload, name = "uploaded"),
    # path('signup/', views.signup, name='signup'), # User [C]reate
    # path('login/', views.login, name='login'), # Session [C]reate
    # path('logout/', views.logout, name='logout'), # Session [D]elete
    # path('delete/', views.delete, name='delete'), # User [D]elete
    # path('edit/', views.edit, name='edit'), # User [U]pdate
    # path('password/', views.password, name='password'), # (Password) [U]pdate
    # path('<str:username>/', views.profile, name='profile'),
]

documents/models.py
from django.db import models


class Document(models.Model):
    description = models.CharField(max_length=255, blank=True)
    markdown = models.FileField(upload_to='documents/')
    uploaded_at = models.DateTimeField(auto_now_add=True)

    @property
    def markdown_content(self):
        return self.markdown.read().decode('utf-8')

    @classmethod
    def search_in_markdown(cls, query):
        documents = cls.objects.all()
        pk_list = [ document.pk for document in documents if query in document.markdown_content ]
        return cls.objects.filter(pk__in = pk_list)

documents/forms.py
from django import forms # new 
from .models import Document#new 
# from django.contrib.auth.forms import UserChangeForm
# from django.contrib.auth import get_user_model


class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ('markdown',)


# class CustomUserChangeForm(UserChangeForm):
#     class Meta:
#         model = get_user_model()#=> auth.User
#         fields = ('username', 'email', 'first_name','last_name')

        

documents/views.py
from django.shortcuts import render, redirect
from .forms import DocumentForm
from .models import Document


def search(request):
    form = DocumentForm()
    documents = Document.objects.all()
    context = {
        'form': form,
        'documents' : documents, 
    }
    return render(request, 'documents/search.html', context)


def result(request):
    query = request.GET.get('q')
    # object_list = City.objects.filter(
    #     Q(name__icontains=query) | Q(state__icontains=query)
    # )

    # 제목만 검색하던 v2 버전 
    # documents = Document.objects.filter(
    #     Q(file__icontains=query)
    # )

    # 내용도 검색할 수 있는 v3 버전 
    documents = Document.search_in_markdown(query)

    context = {
        # 'object_list': object_list,
        'query' : query,
        'documents': documents,
    }
    return render(request, 'documents/result.html', context)


def index(request):
    documents = Document.objects.all()
    context = {
        'documents': documents,
    }
    return render(request, 'documents/index.html', context)

def new(request):
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('documents:index')
    else:
        form = DocumentForm()
    context = {
        'form': form,
    }
    return render(request, 'documents/new.html', context)


def delete(request, pk):
    document = Document.objects.get(pk=pk)
    if request.method == 'POST':
        document.delete()
    return redirect('documents:index')

documents/templates/documents/index.html
{% extends 'base.html' %}

{% block body %}

<div class = "login-button"> 
    {% if user.is_active %}
    <form action="{% url 'accounts:logout' %}" method="POST">
      {% csrf_token %}
      <input type="submit" class= "btn btn-primary" value= "logout">
    </form>
    {% else %}
    <form action="{% url 'accounts:login' %}" method="POST">
      {% csrf_token %}
      <input type="submit" class= "btn btn-primary" value= "login">
    <form action="{% url 'accounts:signup'%}" method= "POST">
      {% csrf_token %}
      <input type="submit" class= "btn btn-primary" value= "signup">
    </form>
    {% endif %} 
  </div>
  
    <h1>
        <span>문서 목록</span>
    </h1>

    
    <div class="index mx-auto mt-5">
        <a href="{% url 'documents:search' %}" class="btn btn-primary">Search</a>
        <a href="{% url 'documents:new' %}" class="btn btn-primary">New</a>
    </div>
    <ul> 
        {% for document in documents %}
        <div class="mx-auto card" style="width: 40rem;"> 
            <div class="card-body" >
                <a href="{{ document.markdown.url }}">
                    {{ document.markdown }}
                </a>
                <form action="{% url 'documents:delete' document.pk %}" method="POST">
                    {% csrf_token %}
                    <input type="submit" value="Delete">
                </form>
            </div>
        </div>
        {% endfor %}
    </ul>

{% endblock %}

documents/templates/documents/new.html
{% extends 'base.html' %}

{% block body %}

<div class = "login-button"> 
    {% if user.is_active %}
    <form action="{% url 'accounts:logout' %}" method="POST">
      {% csrf_token %}
      <input type="submit" class= "btn btn-primary" value= "logout">
    </form>
    {% else %}
    <form action="{% url 'accounts:login' %}" method="POST">
      {% csrf_token %}
      <input type="submit" class= "btn btn-primary" value= "login">
    <form action="{% url 'accounts:signup'%}" method= "POST">
      {% csrf_token %}
      <input type="submit" class= "btn btn-primary" value= "signup">
    </form>
    {% endif %} 
  </div>

    <h1>
        <span>문서 추가</span>
    </h1>

    <div class="new mx-auto mt-5">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }} 
            <input type="submit" value="Create">
        </form>
    </div>
{% endblock %}

documents/templates/documents/result.html
{% extends 'base.html' %}

{% load document_extras %}

{% block body %}
<div class = "login-button"> 
  {% if user.is_active %}
  <form action="{% url 'accounts:logout' %}" method="POST">
    {% csrf_token %}
    <input type="submit" class= "btn btn-primary" value= "logout">
  </form>
  {% else %}
  <form action="{% url 'accounts:login' %}" method="POST">
    {% csrf_token %}
    <input type="submit" class= "btn btn-primary" value= "login">
  <form action="{% url 'accounts:signup'%}" method= "POST">
    {% csrf_token %}
    <input type="submit" class= "btn btn-primary" value= "signup">
  </form>
  {% endif %} 
</div>


  <h1>
    <span>검색 결과</span>
  </h1>
  <!-- Search Form  -->
    <form action="{% url 'documents:result' %}" method="GET">
      <div class="mx-auto mt-5 search-bar input-group mb-3">
        <input name="q" class="form-control rounded-pill" type="text" placeholder="Search..." value="{{ query }}" aria-describedby="basic-addon2">
        <input type="submit" class="btn btn-outline-primary" value="Search">
        
      </div>
      <div class="mx-auto search-bar input-group mb-3">
        <a href="{% url 'documents:search' %}">
          Return to home
        </a>
      </div>
    </form>


    <ul>
        {% for document in documents %}
 
          <div class="mx-auto card" style="width: 40rem;"> 
            <div class="card-body">
              <a href="{{ document.markdown.url }}"> {{ document.markdown }} </a>
              <p>{{ document.markdown_content|highlight:query|safe }}</p>
            </div>
          </div>

        {% endfor %}
    </ul>


{% endblock %}

documents/templates/documents/search.html
{% extends 'base.html' %}

{% load static %}

{% block body %}
  <div class = "login-button"> 
    {% if user.is_active %}
    <form action="{% url 'accounts:logout' %}" method="POST">
      {% csrf_token %}
      <input type="submit" class= "btn btn-primary" value= "logout">
    </form>
    {% else %}
    <form action="{% url 'accounts:login' %}" method="POST">
      {% csrf_token %}
      <input type="submit" class= "btn btn-primary" value= "login">
    <form action="{% url 'accounts:signup'%}" method= "POST">
      {% csrf_token %}
      <input type="submit" class= "btn btn-primary" value= "signup">
    </form>
    {% endif %} 
  </div>


  <h1>
    <span>C</span><span>o</span><span>o</span><span>g</span><span>l</span><span>e</span>
  </h1>



  <!-- Search Form  -->
  <form action="{% url 'documents:result' %}" method="get">
      <!-- <input name="q" type="text" placeholder="Search..."> -->
    <div class="mx-auto mt-5 search-bar input-group mb-3">
      <input type="text" class="form-control rounded-pill" name="q" placeholder="  Coogle 검색" aria-label="Coogle 검색" aria-describedby="basic-addon2">
      <input type="submit" class = "btn btn-outline-primary" value="Search"> 
    </div>
    <div class="mx-auto search-bar input-group mb-3">
      <a href="{% url 'documents:index' %}">
        My Documents
      </a>
    </div>
  </form>


{% endblock %}